import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Streamline Flow",
  description: "Generated by @ Ashik Shafayet",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <main>
          {/* Loaded pages*/}
          {children}
      </main>
      </body>
    </html>
  );
}
